

services:
  backend:
    build:
      context: ./WebApplication1 # Backend folder containing Dockerfile
      dockerfile: Dockerfile     # Dockerfile inside WebApplication1
    ports:
      - "5000:80"                # Map container port 80 to host port 5000
    environment:
      ASPNETCORE_ENVIRONMENT: Development # Set environment variable for .NET
    depends_on:
      - db                       # Backend depends on the database service
    networks:
      - app-network              # Use a shared network

  frontend:
    build:
      context: ./frontend        # Frontend folder containing Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:80"                # Map container port 80 to host port 3000
    depends_on:
      - backend                  # Frontend depends on backend service
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrongPassword123" # Set a strong SA password
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"              # Map container port 1433 to host port 1433
    volumes:
      - dbdata:/var/opt/mssql    # Persist database data
    networks:
      - app-network

volumes:
  dbdata:                        # Define a named volume for database persistence

networks:
  app-network:
    driver: bridge               # Use bridge network for communication
